# Generated by Django 5.2.6 on 2025-11-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='registradoPor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
